// SMM namespaces
global using SMM.Models;
global using SMM.Models.Difficulties;
global using SMM.Models.Helpers;
global using SMM.Services;
global using SMM.Services.DynamicXAML;
global using SMM.Views;

// Other namespaces
global using System.Globalization;
global using System.Runtime.InteropServices;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Markup;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;